name: Test
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: install
        run: yarn
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
